name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Install Python and PyYAML
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install pyyaml

      - name: Extract project name from application.yml
        id: extract_name
        run: |
          PROJECT_NAME=$(python3 -c "
          import yaml
          with open('src/main/resources/application.yml', 'r') as stream:
              try:
                  config = yaml.safe_load(stream)
                  print(config['spring']['application']['name'])
              except yaml.YAMLError as exc:
                  print(exc)
          ")
          echo "PROJECT_NAME=${PROJECT_NAME}" >> $GITHUB_ENV

      - name: Generate timestamp
        id: generate_timestamp
        run: |
          TIMESTAMP=$(date +"%d-%m-%Y-%H-%M-%S")
          echo "TIMESTAMP=${TIMESTAMP}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            myregistry.com/${{ env.PROJECT_NAME }}:${{ env.TIMESTAMP }}
            myregistry.com/${{ env.PROJECT_NAME }}:latest
