name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Generate timestamp
        id: generate_timestamp
        run: |
          TIMESTAMP=$(date +"%d-%m-%Y-%H-%M-%S")
          echo "TIMESTAMP=${TIMESTAMP}" >> $GITHUB_ENV

      - name: Extract project name from application.properties
        id: extract_name
        run: |
          PROJECT_NAME=$(grep -E '^spring\.application\.name=' src/main/resources/application.properties | cut -d '=' -f 2)
          echo "PROJECT_NAME=${PROJECT_NAME}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            sandrzejczak/${{ env.PROJECT_NAME }}:${{ env.TIMESTAMP }}
            sandrzejczak/${{ env.PROJECT_NAME }}:latest
          build-args: |
            PROJECT_NAME=${{ env.PROJECT_NAME }}
            BUILD_DATE=${{ env.TIMESTAMP }}
