name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          # Get project name from application.yml
          PROJECT_NAME=$(python3 -c "
          import yaml
          with open('src/main/resources/application.yml', 'r') as stream:
              try:
                  config = yaml.safe_load(stream)
                  print(config['spring']['application']['name'])
              except yaml.YAMLError as exc:
                  print(exc)
          ")
          
          # Default to "default-name" if PROJECT_NAME is empty
          PROJECT_NAME=${PROJECT_NAME:-default-name}

          # Get the current date
          DATE=$(date +"%d-%m-%Y-%H-%M-%S")

          # Generate image tag
          IMAGE_TAG="${PROJECT_NAME}-test:${DATE}"

          # Build Docker image
          docker build --build-arg PROJECT_NAME=${PROJECT_NAME} -t "${IMAGE_TAG}" .

          # Tag and push the image
          FINAL_TAG="sandrzejczak/${PROJECT_NAME}:${DATE}-test"
          docker tag "${IMAGE_TAG}" "${FINAL_TAG}"
          docker push "${FINAL_TAG}"

      - name: Post image build information
        run: |
          echo "PROJECT_NAME: $PROJECT_NAME"
          echo "IMAGE_TAG: $IMAGE_TAG"
          echo "FINAL_TAG: $FINAL_TAG"
